export const enum Ctrl {
  Move = 'MOV',
  Add = 'ADD',
  Sub = 'SUB',
  Mul = 'MUL',
  Div = 'DIV',
  Mod = 'MOD',
  And = 'AND',
  Or = 'OR',
  Not = 'NOT',
  DefineLabel = 'LBL',
  Jump = 'JMP',
  JumpFalse = 'JF',
  Call = 'CALL',
  Return = 'RET',
  Push = 'PUSH',
  Pop = 'POP',
  Peek = 'PEEK',
  Print = 'PRINT',
  StepIn = 'STN',
  StepOut = 'STO',
  // Operators
  Equal = 'EQ',
  NotEqual = 'NE',
  Less = 'LT',
  LessOrEqual = 'LE',
  Greater = 'GT',
  GreaterOrEqual = 'GE',
  Negate = 'NEG',
  NegateBool = 'NEGB',
}
